### ISSUE TITLE
hap.kin0 not found

### ISSUE THREAD

**Issue by sjoerdvanalten** [AlexTISYoung/SNIPar#14]
Hello,

I have installed the package and am trying to familiarize myself with it through the tutorial. However, when running the first line in the tutorial I get an error: 
```
$python ibd.py example/sample --king example/sample.king.kin0 --agesex example/sample.agesex --map example/sample.genetic_map.txt --outprefix example/ --threads 4

2021-10-18 10:03:26 INFO     start
Traceback (most recent call last):
  File "ibd.py", line 234, in <module>
    kin_header = np.array(open(kinfile,'r').readline().split('\t'))
FileNotFoundError: [Errno 2] No such file or directory: '/disk/genetics4/ukb/alextisyoung/haplotypes/relatives/bedfiles/hap.kin0'
```
Any idea what could have gone wrong? (testing the packages after installation using pytest went fine I believe)

**Comment by AlexTISYoung** [comment]
Hi,

Thanks for your email, and apologies for the difficulties you've had. The
error in question was caused by an error we made in updating the software
with some new developments we had made on IBD inference. This should be
solved by updating to the latest version of the software. Please pull the
latest version of the master branch with 'git pull origin master' in the
SNIPar directory, and reinstall the package.

Let me know if you have any further difficulties.

Thanks,

Alex.

**Comment by sjoerdvanalten** [comment]
Hi Alex,

Thank you for your quick response. re-installing resolved the issue.

Kind regards, Sjoerd
